name: vinas_mobile
description: Aplicación móvil Viñas AI para clasificar variedades de uva mediante IA
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.5.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.9
  go_router: ^14.2.0
  google_nav_bar: ^5.0.7
  image_picker: ^1.1.1
  geolocator: ^14.0.2
  geocoding: ^3.0.0
  permission_handler: ^12.0.1
  camera: ^0.10.5
  flutter_map: ^7.0.0 
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  flutter_linkify: ^6.0.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/tutorial/
    - assets/inicio/
    - assets/navbar/
    - assets/biblioteca/
    - assets/inicio/
    - assets/foro/
    - assets/foto/
    - assets/home/